name = "my-typescript-worker"
type = "javascript"
# zone_id = ""
account_id = "6733500ac6d08278f562a7c21b82ad9b"
# route = ""
workers_dev = true
compatibility_date = "2022-04-03"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
